### ISSUE TITLE
Behat Command not exists in blt 12

### ISSUE THREAD

**Issue by christianwiedemann** [docksal/blt-docksal#5]
Hi, 

with blt 12 I get an exception when I install blt-docksal.

```
Fatal error: Uncaught Error: Class 'Acquia\Blt\Robo\Commands\Tests\BehatCommand' not found in /var/www/vendor/docksal/blt-docksal/src/Blt/Plugin/Commands/BehatDocksalCommand.php:7
Stack trace:
#0 /var/www/vendor/composer/ClassLoader.php(444): include()
```
Seems that blt removed behat support. Not sure how to solve this. Remove the command?

**Comment by sandipsmarty** [comment]
I am also facing the same issue after upgrading the BLT to **12.5.1**. Not sure what would be best approach to fix this issue.

**Comment by sandipsmarty** [comment]
Behat plugin has been moved out from BLT 12 and `acquia/blt-behat` plugin need to be added separately. As per **BLT 12** in `blt-docksal/src/Blt/Plugin/Commands/BehatDocksalCommand.php` file on **line 5** it should be `use Acquia\BltBehat\Blt\Plugin\Commands\BehatCommand;` instead of `use Acquia\Blt\Robo\Commands\Tests\BehatCommand;` Probably this can be implemented with BLT version check to get backward compatibility.

@asgorobets, @shelane : Could you please help on this.

**Comment by shelane** [comment]
@lpeabody would you look at this because I don’t have Behat running.

**Comment by lpeabody** [comment]
Ugh yeah makes sense. We'll need to update composer.json so that is requires the new behat BLT plugin also.

**Comment by shelane** [comment]
That’s fine for users of BLT 12. Do we need to branch for 11?
